# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Field_on_grid": "field_on_grid.ipynb",
         "NTHREAD": "field_on_grid.ipynb",
         "EPS": "field_on_grid.ipynb"}

modules = ["field_on_grid.py"]

doc_url = "https://{saitosmst}.github.io/two_point_clustering/"

git_url = "https://github.com/{saitosmst}/two_point_clustering/tree/{branch}/"

def custom_doc_links(name): return None
